version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile/app.dockerfile
    ports:
      - "5000:5000"
    networks:
      - app_network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    build:
      context: .
      dockerfile: dockerfile/redis.dockerfile
    ports:
      - "6379:6379"
    networks:
      - app_network
networks:
  app_network:

