apiVersion: apps/v1
kind: Deployment
metadata:
  name: giropops-senha-deployment
  namespace: giropops
  labels:
    app: giropops-senha-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: giropops-senha-deployment
  template:
    metadata:
      labels:
        app: giropops-senha-deployment
    spec:
      containers:
      - name: giropops-senha-container
        image: mmazoni/linuxtips-giropops-senhas:3.0
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: localhost
        - name: REDIS_PORT
          value: "6379"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 3
      - name: redis
        image: cgr.dev/chainguard/redis:latest
        ports:
        - containerPort: 6379
