apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.6.3/components.yaml
  - ../../base
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/manifests/grafana-service.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/manifests/prometheus-service.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/manifests/alertmanager-service.yaml

patches:
  - target:
      kind: Service
      name: giropops-senhas
      namespace: giropops
      version: v1
    path: service-app.yml

  - target:
      kind: Service
      name: grafana
      namespace: monitoring
    patch: |-
      - op: add
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 31603

  - target:
      kind: Service
      name: prometheus-k8s
      namespace: monitoring
      version: v1
    patch: |-
      - op: add
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 31602

  - target:
      kind: Service
      name: alertmanager-main
      namespace: monitoring
      version: v1
    patch: |-
      - op: add
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 31604
