---
name: Continous Integration

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'dockerfile/app.dockerfile'

env:
  DOCKERHUB_USERNAME: mmazoni
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_IMAGE: mmazoni/linuxtips-giropops-senhas

jobs:
  lint:
    name: Kubernetes Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Kube-linter
        uses: stackrox/kube-linter-action@v1.0.4
        with:
          directory: manifests
          config: .kube-linter.yml

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfile/app.dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            ${{ env.DOCKER_IMAGE }}:latest
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.2.0
      - name: Sign image
        run: |
          cosign sign --yes ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          cosign sign --yes ${{ env.DOCKER_IMAGE }}:latest
      - name: Verify image
        run: |
          cosign verify ${{ env.DOCKER_IMAGE }}:${{ github.sha }} ${{ env.DOCKER_IMAGE }}:latest \
            --certificate-identity https://github.com/MMazoni/giropops-senha-linuxtips/.github/workflows/deploy.yml@refs/heads/main \
            --certificate-oidc-issuer https://token.actions.githubusercontent.com | jq
    needs: lint

